-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local Color4 = '#82AAFF'
local Color5 = '#a4ceee'
local Color10 = '#d29ffc'
local Color8 = '#c792ea'
local Color12 = '#011627'
local Color17 = '#103362'
local Color3 = '#A170C6'
local Color0 = '#999999'
local Color2 = '#8dec95'
local Color9 = '#87aff4'
local Color20 = '#d2dee7'
local Color16 = '#30222f'
local Color1 = '#bcf0c0'
local Color15 = '#152c30'
local Color7 = '#00bff9'
local Color18 = '#010e1a'
local Color19 = '#5f7e97'
local Color11 = '#219fd5'
local Color13 = '#a7dbf7'
local Color14 = '#0b2942'
local Color6 = '#6dbdfa'

highlight('Comment', nil, Color0, 'italic')
highlight('String', nil, Color1, nil)
highlight('Number', nil, Color2, nil)
highlight('Constant', nil, Color3, nil)
highlight('TSCharacter', nil, Color4, nil)
highlight('Identifier', nil, Color5, 'italic')
highlight('Type', nil, Color6, nil)
highlight('Keyword', nil, Color7, 'italic')
highlight('Operator', nil, Color7, 'italic')
highlight('Type', nil, Color8, 'italic')
highlight('Function', nil, Color9, 'italic')
highlight('Type', nil, Color10, nil)
highlight('Error', nil, Color6, nil)
highlight('StatusLine', nil, Color11, nil)
highlight('WildMenu', Color12, Color13, nil)
highlight('Pmenu', Color12, Color13, nil)
highlight('PmenuSel', Color13, Color14, nil)
highlight('PmenuThumb', Color12, Color13, nil)
highlight('DiffAdd', Color15, nil, nil)
highlight('DiffDelete', Color16, nil, nil)
highlight('Normal', Color12, Color13, nil)
highlight('Visual', Color17, nil, nil)
highlight('CursorLine', Color17, nil, nil)
highlight('ColorColumn', Color17, nil, nil)
highlight('SignColumn', Color12, nil, nil)
highlight('LineNr', nil, Color11, nil)
highlight('TabLine', Color18, Color19, nil)
highlight('TabLineSel', Color20, Color14, nil)
highlight('TabLineFill', Color18, Color19, nil)
highlight('TSPunctDelimiter', nil, Color13, nil)

link('TelescopeNormal', 'Normal')
link('TSKeyword', 'Keyword')
link('Conditional', 'Operator')
link('Repeat', 'Conditional')
link('TSConstBuiltin', 'TSVariableBuiltin')
link('Folded', 'Comment')
link('TSFloat', 'Number')
link('TSParameter', 'Constant')
link('TSType', 'Type')
link('TSPunctBracket', 'MyTag')
link('CursorLineNr', 'Identifier')
link('TSNumber', 'Number')
link('TSComment', 'Comment')
link('TSConstant', 'Constant')
link('NonText', 'Comment')
link('Operator', 'Keyword')
link('TSLabel', 'Type')
link('TSFuncMacro', 'Macro')
link('Macro', 'Function')
link('Whitespace', 'Comment')
link('TSParameterReference', 'TSParameter')
link('TSConditional', 'Conditional')
link('TSTagDelimiter', 'Type')
link('TSString', 'String')
link('TSRepeat', 'Repeat')
link('TSTag', 'MyTag')
link('TSOperator', 'Operator')
link('TSFunction', 'Function')
link('TSPunctSpecial', 'TSPunctDelimiter')
link('TSField', 'Constant')
link('TSProperty', 'TSField')
link('TSNamespace', 'TSType')
